package Entites;
// Generated 18 mai 2020 00:26:42 by Hibernate Tools 4.3.1



/**
 * ClientParticulier generated by hbm2java
 */
public class ClientParticulier  implements java.io.Serializable {


     private String numCin;
     private String nom;
     private String prenom;
     private String adresse;
     private String numTel;

    public ClientParticulier() {
    }

    public ClientParticulier(String numCin, String nom, String prenom, String adresse, String numTel) {
       this.numCin = numCin;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.numTel = numTel;
    }
   
    public String getNumCin() {
        return this.numCin;
    }
    
    public void setNumCin(String numCin) {
        this.numCin = numCin;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getNumTel() {
        return this.numTel;
    }
    
    public void setNumTel(String numTel) {
        this.numTel = numTel;
    }




}


