package Entites;
// Generated 18 mai 2020 00:26:42 by Hibernate Tools 4.3.1



/**
 * ClientEntreprise generated by hbm2java
 */
public class ClientEntreprise  implements java.io.Serializable {


     private String raisonSociale;
     private String nom;
     private String prenom;
     private String fonction;
     private String adresse;
     private String numTelephone;
     private String courrierElectr;

    public ClientEntreprise() {
    }

    public ClientEntreprise(String raisonSociale, String nom, String prenom, String fonction, String adresse, String numTelephone, String courrierElectr) {
       this.raisonSociale = raisonSociale;
       this.nom = nom;
       this.prenom = prenom;
       this.fonction = fonction;
       this.adresse = adresse;
       this.numTelephone = numTelephone;
       this.courrierElectr = courrierElectr;
    }
   
    public String getRaisonSociale() {
        return this.raisonSociale;
    }
    
    public void setRaisonSociale(String raisonSociale) {
        this.raisonSociale = raisonSociale;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getNumTelephone() {
        return this.numTelephone;
    }
    
    public void setNumTelephone(String numTelephone) {
        this.numTelephone = numTelephone;
    }
    public String getCourrierElectr() {
        return this.courrierElectr;
    }
    
    public void setCourrierElectr(String courrierElectr) {
        this.courrierElectr = courrierElectr;
    }




}


