package Entites;
// Generated 18 mai 2020 00:26:42 by Hibernate Tools 4.3.1



/**
 * Commercial generated by hbm2java
 */
public class Commercial  implements java.io.Serializable {


     private String codeUnique;
     private String nom;
     private String prenom;
     private int salaireBase;
     private String fonction;
     private int numOrdre;
     private int tauxCommiss;

    public Commercial() {
    }

    public Commercial(String codeUnique, String nom, String prenom, int salaireBase, String fonction, int numOrdre, int tauxCommiss) {
       this.codeUnique = codeUnique;
       this.nom = nom;
       this.prenom = prenom;
       this.salaireBase = salaireBase;
       this.fonction = fonction;
       this.numOrdre = numOrdre;
       this.tauxCommiss = tauxCommiss;
    }
   
    public String getCodeUnique() {
        return this.codeUnique;
    }
    
    public void setCodeUnique(String codeUnique) {
        this.codeUnique = codeUnique;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public int getSalaireBase() {
        return this.salaireBase;
    }
    
    public void setSalaireBase(int salaireBase) {
        this.salaireBase = salaireBase;
    }
    public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }
    public int getNumOrdre() {
        return this.numOrdre;
    }
    
    public void setNumOrdre(int numOrdre) {
        this.numOrdre = numOrdre;
    }
    public int getTauxCommiss() {
        return this.tauxCommiss;
    }
    
    public void setTauxCommiss(int tauxCommiss) {
        this.tauxCommiss = tauxCommiss;
    }




}


