package Entites;
// Generated 18 mai 2020 00:26:42 by Hibernate Tools 4.3.1



/**
 * EquipeCommerciale generated by hbm2java
 */
public class EquipeCommerciale  implements java.io.Serializable {


     private Integer id;
     private String nomEquipe;
     private String typeActivEquipe;
     private String responsableEquipe;
     private String codeUnique;
     private String nom;
     private String prenom;
     private String fonction;
     private int salaireDeBase;
     private int tauxCommis;
     private String numOrdre;

    public EquipeCommerciale() {
    }

    public EquipeCommerciale(String nomEquipe, String typeActivEquipe, String responsableEquipe, String codeUnique, String nom, String prenom, String fonction, int salaireDeBase, int tauxCommis, String numOrdre) {
       this.nomEquipe = nomEquipe;
       this.typeActivEquipe = typeActivEquipe;
       this.responsableEquipe = responsableEquipe;
       this.codeUnique = codeUnique;
       this.nom = nom;
       this.prenom = prenom;
       this.fonction = fonction;
       this.salaireDeBase = salaireDeBase;
       this.tauxCommis = tauxCommis;
       this.numOrdre = numOrdre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomEquipe() {
        return this.nomEquipe;
    }
    
    public void setNomEquipe(String nomEquipe) {
        this.nomEquipe = nomEquipe;
    }
    public String getTypeActivEquipe() {
        return this.typeActivEquipe;
    }
    
    public void setTypeActivEquipe(String typeActivEquipe) {
        this.typeActivEquipe = typeActivEquipe;
    }
    public String getResponsableEquipe() {
        return this.responsableEquipe;
    }
    
    public void setResponsableEquipe(String responsableEquipe) {
        this.responsableEquipe = responsableEquipe;
    }
    public String getCodeUnique() {
        return this.codeUnique;
    }
    
    public void setCodeUnique(String codeUnique) {
        this.codeUnique = codeUnique;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }
    public int getSalaireDeBase() {
        return this.salaireDeBase;
    }
    
    public void setSalaireDeBase(int salaireDeBase) {
        this.salaireDeBase = salaireDeBase;
    }
    public int getTauxCommis() {
        return this.tauxCommis;
    }
    
    public void setTauxCommis(int tauxCommis) {
        this.tauxCommis = tauxCommis;
    }
    public String getNumOrdre() {
        return this.numOrdre;
    }
    
    public void setNumOrdre(String numOrdre) {
        this.numOrdre = numOrdre;
    }




}


