package Entites;
// Generated 18 mai 2020 00:26:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Historique generated by hbm2java
 */
public class Historique  implements java.io.Serializable {


     private Integer id;
     private String raisonSocial;
     private String idclient;
     private String typeClient;
     private String nomEquipe;
     private String nomComm;
     private String prenomComm;
     private String respEquipe;
     private String numordre;
     private Date dateEdition;

    public Historique() {
    }

    public Historique(String raisonSocial, String idclient, String typeClient, String nomEquipe, String nomComm, String prenomComm, String respEquipe, String numordre, Date dateEdition) {
       this.raisonSocial = raisonSocial;
       this.idclient = idclient;
       this.typeClient = typeClient;
       this.nomEquipe = nomEquipe;
       this.nomComm = nomComm;
       this.prenomComm = prenomComm;
       this.respEquipe = respEquipe;
       this.numordre = numordre;
       this.dateEdition = dateEdition;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRaisonSocial() {
        return this.raisonSocial;
    }
    
    public void setRaisonSocial(String raisonSocial) {
        this.raisonSocial = raisonSocial;
    }
    public String getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(String idclient) {
        this.idclient = idclient;
    }
    public String getTypeClient() {
        return this.typeClient;
    }
    
    public void setTypeClient(String typeClient) {
        this.typeClient = typeClient;
    }
    public String getNomEquipe() {
        return this.nomEquipe;
    }
    
    public void setNomEquipe(String nomEquipe) {
        this.nomEquipe = nomEquipe;
    }
    public String getNomComm() {
        return this.nomComm;
    }
    
    public void setNomComm(String nomComm) {
        this.nomComm = nomComm;
    }
    public String getPrenomComm() {
        return this.prenomComm;
    }
    
    public void setPrenomComm(String prenomComm) {
        this.prenomComm = prenomComm;
    }
    public String getRespEquipe() {
        return this.respEquipe;
    }
    
    public void setRespEquipe(String respEquipe) {
        this.respEquipe = respEquipe;
    }
    public String getNumordre() {
        return this.numordre;
    }
    
    public void setNumordre(String numordre) {
        this.numordre = numordre;
    }
    public Date getDateEdition() {
        return this.dateEdition;
    }
    
    public void setDateEdition(Date dateEdition) {
        this.dateEdition = dateEdition;
    }




}


